### ISSUE TITLE
Unable to reduce the delay for first data in each burst

### ISSUE THREAD

**Issue by sahanapalesh** [muneeb-mbytes/axi4_avip#7]
Branch name :  logic_branch
File name :       axi4_master_driver_bfm
Task name :      axi4_write_data_channel_task
Testname :       axi4_blocking_write_read_test

Issue :  For each transaction(burst), **_the first data in a transfer_** is taking and extra clock cycle as shown in **_108ns and 570ns_**. This leads to **_sampling of data twice_** at the monitor end.

![Capture](https://user-images.githubusercontent.com/91043932/150486675-1e803fde-6afc-4695-b2ae-571959c63fde.PNG)

**Comment by muneebullashariff** [comment]
Since the solution was discussed, please go ahead and fix the issue and close the ticket.

**Comment by sahanapalesh** [comment]
Thank you for helping in resolving the issue.. The ticket will be closed.
